/**
 * Central route registry for authenticated app pages.
 * Use these constants instead of hardcoded path strings.
 */
export const routes = {
    home: '/dashboard',
    onboarding: '/dashboard/onboarding',
    profile: '/profile',
    selectAccount: '/select-account',

    sales: {
        root: '/sales',
        list: '/sales/list',
        new: '/sales/new',
        detail: (id: string) => `/sales/${id}` as const,
        invoice: (id: string) => `/sales/${id}/invoice` as const,
        pos: '/sales/pos',
        customerPayments: '/sales/customer-payments',
        customerLedger: '/sales/customer-ledger',
        delivery: '/sales/delivery',
        returns: '/sales/returns',
        returnDetail: (id: string) => `/sales/returns/${id}` as const,
        orders: '/sales/orders',
        orderDetail: (id: string) => `/sales/orders/${id}` as const,
        quotes: '/sales/quotes',
        quoteDetail: (id: string) => `/sales/quotes/${id}` as const,
        warrantyClaims: '/sales/warranty-claims',
        cashierSessions: '/sales/cashier-sessions',
        loyalty: '/sales/loyalty',
        crm: {
            tasks: '/crm/tasks',
            campaigns: '/crm/campaigns',
        },
        customers: '/sales/customers',
        customerDetail: (id: string) => `/sales/customers/${id}` as const,
        customerHistory: (id: string) => `/sales/customers/${id}/history` as const,
        customerDueAging: '/sales/customers/reports/due-aging',
        customerGroups: '/sales/customer-groups',
        priceLists: '/sales/price-lists',
        priceListDetail: (id: string) => `/sales/price-lists/${id}` as const,
        territories: '/sales/territories',
        reports: {
            summary: '/sales/reports/summary',
            products: '/sales/reports/products',
            monthly: '/sales/reports/monthly',
            customers: '/sales/reports/customers',
            consolidated: '/sales/reports/consolidated',
            branchReport: '/sales/reports/branch-report',
        },
    },

    purchases: {
        root: '/purchases',
        list: '/purchases/list',
        purchaseDetail: (id: string) => `/purchases/${id}` as const,
        purchaseInvoice: (id: string) => `/purchases/${id}/invoice` as const,
        supplierPayments: '/purchases/supplier-payments',
        supplierLedger: '/purchases/supplier-ledger',
        orders: '/purchases/orders',
        orderDetail: (id: string) => `/purchases/orders/${id}` as const,
        orderInvoice: (id: string) => `/purchases/orders/${id}/invoice` as const,
        quotations: '/purchases/quotations',
        quotationDetail: (id: string) => `/purchases/quotations/${id}` as const,
        returns: '/purchases/returns',
        returnDetail: (id: string) => `/purchases/returns/${id}` as const,
        suppliers: '/purchases/suppliers',
        reports: {
            summary: '/purchases/reports/summary',
            byProduct: '/purchases/reports/by-product',
            bySupplier: '/purchases/reports/by-supplier',
        },
    },

    accounting: {
        root: '/accounting',
        vouchers: '/accounting/vouchers',
        journal: '/accounting/journal',
        journalDetail: (id: string) => `/accounting/journal/${id}` as const,
        ledger: '/accounting/ledger',
        reconciliation: '/accounting/reconciliation',
        reconciliationBank: '/accounting/reconciliation/bank',
        coa: '/accounting/coa',
        postingRules: '/accounting/posting-rules',
        costCenters: '/accounting/cost-centers',
        fiscalPeriods: '/accounting/fiscal-periods',
        fixedAssets: '/accounting/fixed-assets',
        openingBalances: '/accounting/opening-balances',
        recurringJournals: '/accounting/recurring-journals',
        expenses: '/accounting/expenses',
        expenseCategories: '/accounting/expenses/categories',
        expenseReports: '/accounting/expenses/reports',
        loans: '/accounting/loans',
        reports: {
            pl: '/accounting/reports/pl',
            balanceSheet: '/accounting/reports/balance-sheet',
            cashbook: '/accounting/reports/cashbook',
            bankbook: '/accounting/reports/bankbook',
            trialBalance: '/accounting/reports/trial-balance',
            arAging: '/accounting/reports/ar-aging',
            apAging: '/accounting/reports/ap-aging',
            cashFlow: '/accounting/reports/cash-flow',
            vatTax: '/accounting/reports/vat-tax',
            comparativePl: '/accounting/reports/comparative-pl',
            budgetVsActual: '/accounting/reports/budget-vs-actual',
            financialRatios: '/accounting/reports/financial-ratios',
        },
    },

    inventory: {
        root: '/inventory',
        products: '/inventory/products',
        transfers: '/inventory/transfers',
        transferDetail: (id: string) => `/inventory/transfers/${id}` as const,
        shrinkage: '/inventory/shrinkage',
        stockTakes: '/inventory/stock-takes',
        stockTakeDetail: (id: string) => `/inventory/stock-takes/${id}` as const,
        labels: '/inventory/labels',
        ledger: '/inventory/ledger',
        categories: '/inventory/categories',
        settings: '/inventory/settings',
        brands: '/inventory/brands',
        reports: {
            reorder: '/inventory/reports/reorder',
            shrinkage: '/inventory/reports/shrinkage',
            valuation: '/inventory/reports/valuation',
        },
    },

    crm: {
        root: '/crm',
        customers: '/crm/customers',
        leads: '/crm/leads',
        leadDetail: (id: string) => `/crm/leads/${id}` as const,
        tasks: '/crm/tasks',
        campaigns: '/crm/campaigns',
    },

    hr: {
        root: '/hr',
        employees: '/hr/employees',
        employeeDetail: (id: string) => `/hr/employees/${id}` as const,
        departments: '/hr/employees/departments',
        designations: '/hr/employees/designations',
        attendance: '/hr/attendance',
        leaves: '/hr/leaves',
        salaryPayments: '/hr/salary-payments',
    },

    storefront: {
        root: '/storefront',
        settings: '/storefront/settings',
    },

    settings: {
        root: '/settings',
        branding: '/settings/branding',
        tax: '/settings/tax',
        auditLogs: '/settings/audit-logs',
        loyalty: '/settings/loyalty',
        sms: '/settings/sms',
        reports: '/settings/reports',
        discountCodes: '/settings/discount-codes',
        paymentMethods: '/settings/payment-methods',
        sales: '/settings/sales',
        team: '/team',
        counters: '/settings/counters',
        localization: '/settings/localization',
    },

    admin: {
        root: '/admin',
        tenants: '/admin/tenants',
        users: '/admin/users',
        feedback: '/admin/feedback',
        support: '/admin/support',
        systemHealth: '/admin/system-health',
        platformSettings: {
            root: '/admin/platform-settings',
            general: '/admin/platform-settings/general',
            email: '/admin/platform-settings/email',
            sms: '/admin/platform-settings/sms',
            payments: '/admin/platform-settings/payments',
            ai: '/admin/platform-settings/ai',
        },
    },

    billing: '/billing',
    team: '/team',
    help: '/help',
    support: '/support',
    smsCredits: '/sms-credits',
    aiCredits: '/ai-credits',
    manufacturing: '/manufacturing',
} as const;