/**
 * All authenticated nav targets: sidebar links, hub cards, settings quick links,
 * and admin overview links. Keep in sync with Sidebar.tsx and module hub pages.
 */
export const NAV_ROUTES: { path: string; label: string }[] = [
    // Dashboard
    { path: '/dashboard', label: 'Dashboard' },

    // Sales — sidebar + hub
    { path: '/sales', label: 'Sales Overview' },
    { path: '/sales/pos', label: 'POS' },
    { path: '/sales/list', label: 'All Sales' },
    { path: '/sales/new', label: 'New Sales Entry' },
    { path: '/sales/cashier-sessions', label: 'Cashier Sessions' },
    { path: '/sales/customer-payments', label: 'Customer Payments' },
    { path: '/sales/customer-ledger', label: 'Customer Ledger' },
    { path: '/sales/customers/reports/due-aging', label: 'Due Aging' },
    { path: '/sales/quotes', label: 'Sales Quotations' },
    { path: '/sales/orders', label: 'Sales Orders' },
    { path: '/sales/delivery', label: 'Delivery' },
    { path: '/sales/returns', label: 'Sales Returns' },
    { path: '/sales/warranty-claims', label: 'Warranty Claims' },
    { path: '/storefront', label: 'Storefront Orders' },
    { path: '/storefront/settings', label: 'Storefront Settings' },
    { path: '/sales/customers', label: 'Customers' },
    { path: '/crm', label: 'CRM Overview' },
    { path: '/crm/customers', label: 'CRM Customers' },
    { path: '/crm/leads', label: 'CRM Leads' },
    { path: '/sales/loyalty', label: 'Loyalty Points' },
    { path: '/sales/reports/summary', label: 'Sales Summary' },
    { path: '/sales/reports/products', label: 'Sales by Product' },
    { path: '/sales/reports/consolidated', label: 'Consolidated Report' },
    { path: '/sales/reports/branch-report', label: 'Branch Report' },
    { path: '/sales/customer-groups', label: 'Customer Groups' },
    { path: '/sales/price-lists', label: 'Price Lists' },
    { path: '/sales/territories', label: 'Territories' },
    { path: '/settings/sales', label: 'Sales Settings' },

    // Purchases — sidebar + hub
    { path: '/purchases', label: 'Purchase Overview' },
    { path: '/purchases/list', label: 'All Purchases' },
    { path: '/purchases/supplier-payments', label: 'Supplier Payments' },
    { path: '/purchases/supplier-ledger', label: 'Supplier Ledger' },
    { path: '/purchases/orders', label: 'Purchase Orders' },
    { path: '/purchases/quotations', label: 'Purchase Quotations' },
    { path: '/purchases/returns', label: 'Purchase Returns' },
    { path: '/purchases/reports/summary', label: 'Purchase Summary' },
    { path: '/purchases/reports/by-product', label: 'Purchases by Product' },
    { path: '/purchases/reports/by-supplier', label: 'Purchases by Supplier' },
    { path: '/purchases/suppliers', label: 'Suppliers' },

    // Accounting — sidebar + hub
    { path: '/accounting', label: 'Accounting Overview' },
    { path: '/accounting/vouchers/new', label: 'Voucher Entry' },
    { path: '/accounting/vouchers', label: 'Vouchers' },
    { path: '/accounting/journal', label: 'Journal' },
    { path: '/accounting/ledger', label: 'Accounting Ledger' },
    { path: '/accounting/reconciliation', label: 'Posting Exceptions' },
    { path: '/accounting/expenses', label: 'Expenses' },
    { path: '/accounting/expenses/categories', label: 'Expense Categories' },
    { path: '/accounting/expenses/reports', label: 'Expense Reports' },
    { path: '/accounting/loans', label: 'Loans' },
    { path: '/accounting/reports/pl', label: 'Profit & Loss' },
    { path: '/accounting/reports/balance-sheet', label: 'Balance Sheet' },
    { path: '/accounting/reports/cashbook', label: 'Cashbook' },
    { path: '/accounting/reports/bankbook', label: 'Bankbook' },
    { path: '/accounting/coa', label: 'Chart of Accounts' },
    { path: '/accounting/posting-rules', label: 'Posting Rules' },
    { path: '/accounting/fiscal-periods', label: 'Fiscal Periods' },
    { path: '/accounting/opening-balances', label: 'Opening Balances' },
    { path: '/accounting/cost-centers', label: 'Cost Centers' },
    { path: '/accounting/fixed-assets', label: 'Fixed Assets' },
    { path: '/accounting/recurring-journals', label: 'Recurring Journals' },
    { path: '/accounting/reconciliation/bank', label: 'Bank Reconciliation' },
    { path: '/accounting/reports/trial-balance', label: 'Trial Balance' },
    { path: '/accounting/reports/comparative-pl', label: 'Comparative P&L' },
    { path: '/accounting/reports/ar-aging', label: 'AR Aging' },
    { path: '/accounting/reports/ap-aging', label: 'AP Aging' },
    { path: '/accounting/reports/vat-tax', label: 'VAT / Tax' },
    { path: '/accounting/reports/budget-vs-actual', label: 'Budget vs Actual' },
    { path: '/accounting/reports/cash-flow', label: 'Cash Flow' },
    { path: '/accounting/reports/financial-ratios', label: 'Financial Ratios' },

    // Inventory — sidebar + hub
    { path: '/inventory', label: 'Inventory Overview' },
    { path: '/inventory/products', label: 'Inventory Products' },
    { path: '/inventory/transfers', label: 'Transfers' },
    { path: '/inventory/stock-takes', label: 'Stock Takes' },
    { path: '/inventory/shrinkage', label: 'Shrinkage' },
    { path: '/inventory/labels', label: 'Print Labels' },
    { path: '/inventory/ledger', label: 'Stock Ledger' },
    { path: '/inventory/reports/reorder', label: 'Reorder Report' },
    { path: '/inventory/reports/shrinkage', label: 'Shrinkage Report' },
    { path: '/inventory/reports/valuation', label: 'Valuation Report' },
    { path: '/inventory/brands', label: 'Brands' },
    { path: '/inventory/categories', label: 'Categories' },
    { path: '/inventory/settings', label: 'Inventory Settings' },

    // HR — sidebar + hub
    { path: '/hr', label: 'HR Overview' },
    { path: '/hr/employees', label: 'Employees' },
    { path: '/hr/employees/departments', label: 'Departments' },
    { path: '/hr/employees/designations', label: 'Designations' },
    { path: '/hr/attendance', label: 'Attendance' },
    { path: '/hr/leaves', label: 'Leaves' },
    { path: '/hr/salary-payments', label: 'Salary Payments' },

    // Account settings — sidebar + settings quick links
    { path: '/settings', label: 'Settings' },
    { path: '/billing', label: 'Billing' },
    { path: '/team', label: 'Team & Permissions' },
    { path: '/sms-credits', label: 'SMS Credits' },
    { path: '/ai-credits', label: 'AI Credits' },
    { path: '/settings/audit-logs', label: 'Audit Logs' },
    { path: '/settings/localization', label: 'Localization' },
    { path: '/settings/branding', label: 'Branding' },
    { path: '/settings/tax', label: 'Tax / VAT' },
    { path: '/settings/loyalty', label: 'Loyalty Program Settings' },
    { path: '/settings/sms', label: 'SMS Notifications' },
    { path: '/settings/reports', label: 'Report Emails' },
    { path: '/settings/counters', label: 'Counters' },
    { path: '/settings/discount-codes', label: 'Discount Codes' },
    { path: '/settings/payment-methods', label: 'Payment Methods' },

    // Support & help
    { path: '/support', label: 'Support' },
    { path: '/help', label: 'Help' },

    // Admin — sidebar + hub
    { path: '/admin', label: 'Admin Overview' },
    { path: '/admin/tenants', label: 'Platform Admin Tenants' },
    { path: '/admin/users', label: 'Platform Admin Users' },
    { path: '/admin/feedback', label: 'Feedback' },
    { path: '/admin/support', label: 'Admin Support' },
    { path: '/admin/platform-settings', label: 'Platform Settings' },
    { path: '/admin/platform-settings/general', label: 'Platform Settings General' },
    { path: '/admin/platform-settings/email', label: 'Platform Settings Email' },
    { path: '/admin/platform-settings/sms', label: 'Platform Settings SMS' },
    { path: '/admin/platform-settings/payments', label: 'Platform Settings Payments' },
    { path: '/admin/platform-settings/ai', label: 'Platform Settings AI' },
    { path: '/admin/system-health', label: 'System Health' },
];